### ISSUE TITLE
Join Declaration/Assignment

### ISSUE THREAD

**Issue by JoeStanton** [JoeStanton/babel-js-to-jsx#10]
One major annoyance left over from Livescript compilation is the consistent separation of variable declaration and assignment. Effectively making the JS hoisting property explicit. Eg.

``` livescript
a = 1
```

Transpiles to:

``` js
var a;
a = 1;
```

In non-trivial scenarios this is even worse, as Livescript will join together multiple declarations within the same scope into a single line, eg.

``` javascript
var a, b, c;
a = 1;
b = 2;
c = 3;
```

It'd help to provide an optional transform that reverses this effect. I think it's achievable by transforming the first assignment to the declaration itself, and removing the original declaration _iff_ both statements are within the same scope. If this isn't true I don't think it can be performed safely.

**Comment by JoeStanton** [comment]
@paulroper you had a possible solution for this? Want to PR it?

**Comment by paulroper** [comment]
I didn't hit a solution for multi-line declarations unfortunately, only single line. :disappointed:

**Comment by JoeStanton** [comment]
Can you share the AST explorer sample you had? We can adapt it for multi-line and deal with scoping.

**Comment by paulroper** [comment]
...I didn't save it because I dumb am :+1:

**Comment by paulroper** [comment]
I had a mess around in the AST Explorer again and came up with this:

``` js
export default function ({types: t}) {
  return {
    visitor: {      
      ExpressionStatement(path) {
        if (path.node.expression.type !== "AssignmentExpression") { return; }

        const left = path.node.expression.left;
        const binding = path.scope.bindings[left.name];

        if (binding && !binding.path.shouldSkip) {
          path.replaceWith(
            t.variableDeclaration("var", [t.VariableDeclarator(left, path.node.expression.right)])
          );

          binding.path.remove(); 
        }
      }
    }
  };
}
```

It'll turn:

``` js
var a, b, c;
a = 1;
b = 3;
c = 4;
```

Into:

``` js
var a = 1;
var b = 3;
var c = 4;
```

**Comment by JoeStanton** [comment]
Great! Can you look into a good way to check the scope?

**Comment by paulroper** [comment]
Check the scope of the transformed variable assignments?
