### ISSUE TITLE
Certain Case where UnhoistVariables Plugin and Modules Plugin Won't Play Nicely

### ISSUE THREAD

**Issue by paulroper** [JoeStanton/babel-js-to-jsx#13]
Seems to be related to having two destructured imports in one file:

``` livescript
{div, label, select, option} = require 'react-dom-bridge'
{map, filter, unique-by, compact} = require 'prelude-ls'
```

I narrowed it down to the `AssignmentExpression` part of the Modules plugin. The code above gets transpiled to:

``` jsx
var ref$, div, label, select, option, map, filter, uniqueBy, compact;
ref$ = require('react-dom-bridge'), div = ref$.div, label = ref$.label...
ref$ = require('prelude-ls'), map = ref$.map, filter = ref$.filter...
```

We delete the binding for `ref$` once we've converted the `react-dom-bridge` import and so it doesn't exist when we try to convert the `prelude-ls` import. That means... :boom:

**Comment by JoeStanton** [comment]
Livescript compiled output is pretty gross. How much of a problem is this? You can always disable `UnhoistVariables` as it's a little more experimental than the other transforms.

**Comment by paulroper** [comment]
It's not much of a problem at all, you can just work around it like you said and then unhoist the variables manually

**Comment by JoeStanton** [comment]
:+1:
