### ISSUE TITLE
babel-plugin naming

### ISSUE THREAD

**Issue by bryce-larson** [JoeStanton/babel-js-to-jsx#15]
I believe babel changed their naming for plug-ins, trying to run the following:

```
require("babel-core").transform(code, {
  plugins: ["js-to-jsx", "syntax-jsx"],
}).code
```

Give me this error:

```

<path>../node_modules/babel-core/lib/transformation/file/options/option-manager.js:212
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "js-to-jsx" specified in "base" at 0, attempted to resolve relative to
```

However if I rename the folder:
`mv node_modules/babel-js-to-jsx node_modules/babel-plugin-js-to-jsx`
it is able to find the module.

Consider changing the name of this project to babel-plugin-js-to-jsx.

**Comment by JoeStanton** [comment]
Sigh. Thank you for letting me know, I'll do a rename for the next release!
